version: '3'

services:
  django_app:
    build:
      context: .
      dockerfile: docker/dev/django_app/Dockerfile
    entrypoint: /entrypoint.sh
#    tty: True
    ports:
      - "80:8000"
    restart: "no"
    env_file:
      #      - docker/dev/env/.local.env
      - docker/dev/env/.web.env
      - docker/dev/env/.db.env
    volumes:
      - ./django_proj:/app
    networks:
      - mongo_test
    depends_on:
      - mongo

    logging:
      options:
        max-size: "20m"
        max-file: "3"

  mongo:
    image: mongo
    restart: "no"
    env_file:
      - docker/dev/env/.db.env
    expose:
      - 27017
    networks:
      - mongo_test

  mongo-express:
    image: mongo-express:latest
    restart: "no"
    ports:
      - "8081:8081"
    env_file:
      - docker/dev/env/.db.env
    networks:
      - mongo_test
    depends_on:
      - mongo

networks:
  mongo_test:
    driver: bridge